name: Infra Provisioning through Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (eg..., dev, staging, prod)"
        required: true
        default: "dev"
        type: choice
        options:
        - dev
        - staging
        - prod

      
permissions:
  contents: read
  id-token: write  

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::183114607892:role/github_actions_oidc
          role-session-name: githubactions
          aws-region: "us-west-2"      
          
      # Step: Terraform Init
      - name: Terraform Init
        run: | 
          cd infra/env/${{ github.event.inputs.environment || 'dev' }}
          terraform init
  

      # Step: Terraform Plan
      - name: Terraform Plan
        run: |
          cd infra/env/${{ github.event.inputs.environment || 'dev' }} 
          terraform plan  -out=tfplan
        

      # Step: Apply Terraform Destroy
      - name: Apply Terraform Destroy
        run: |
          cd infra/env/${{ github.event.inputs.environment || 'dev' }}
          terraform init
          terraform destroy -auto-approve
